plugins:
  - jekyll-remote-theme
remote_theme: asstart/just-the-docs
baseurl: /vault
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  rel_url: true
  button: false
mermaid:
  version: 9.1.3
heading_anchors: true
color_scheme: dark
